import "../assets/styles/App.css";
import { useEffect } from "react";
import { Interweave } from "interweave";
import Template from "../components/template";

function Pizzle({ state, setState, data }) {
  console.log("render");
  console.log(state);
  useEffect(() => {
    setState((s) => ({ ...s, current: "q" }));
  }, [setState]);

  const subtitle = (
    <p className="subtitle">
      Wikipedia or AI-Generated? Take a guess and test your skills!
    </p>
  );

  const choose = () => (
    <div className="app">
      {/* <header> {this.topbar()} </header> */}
      {subtitle}

      <div className="article-container">
        <div className="article">
          <Interweave content={data.html} />
        </div>
      </div>

      <div className="ins">
        <div className="button-container">
          {" "}
          <button className="button1" onClick={() => guessed(true)}>
            <span>WIKIPEDIA</span>
          </button>{" "}
        </div>
        <div className="button-container">
          {" "}
          <button className="button2" onClick={() => guessed(false)}>
            <span>AI GENERATED</span>
          </button>{" "}
        </div>
      </div>
    </div>
  );

  // const correct = (
  //   <div className="app">
  //     <header></header>
  //     {subtitle}

  //     <div className="answer-box">something</div>

  //     <div className="article"> something</div>
  //     <div className="ins">
  //       <button className="button1" onClick={() => home()}>
  //         <span>HOME</span>
  //       </button>
  //     </div>
  //   </div>
  // );

  const chosen = () => {
    const stats = JSON.parse(localStorage.getItem("stats"));
    const answerbox =
      "answer-box " + (state.page === 1 ? "correct" : "incorrect");
    return (
      <div className="app">
        {subtitle}

        <div className="chosen-container">
          <div className={answerbox}>
            <h2 className="answer-box">
              {state.page === 1 ? "Correct" : "Incorrect"}
            </h2>
            <h3 className="answer-box">
              {state.page === 1 ? "You're right!" : "You have been deceived!"}{" "}
              Today's article{" "}
              {data.contentType
                ? "was an actual Wikipedia article"
                : "was generated by AI"}
            </h3>
          </div>

          {/* <div className="left-wrapper">
                  L
                </div>

                <div className="right-wrapper">
                  R */}
          <div className="left-wrapper">
            <div className="chosen-article">
              <div className="article">
                <Interweave content={data.html} />
              </div>
            </div>
            <div className="learn-more">
              Want to find out more about this topic?
              <a
                target="_blank"
                rel="noreferrer"
                href={`https://letmegooglethat.com/?q=${data.title}`}
              >
                Click here
              </a>
            </div>
          </div>

          <div className="right-wrapper">
            <div className="stats">
              <h2> people deceived </h2>
              <h1> pi chart </h1>
              <h3> your statistics </h3>
              <h4> {JSON.stringify(stats)} </h4>
              <h4> win rate </h4>
              <h4> {`${(stats.win / (stats.loss + stats.win)) * 100}%`} </h4>
              <h4> -------- </h4>
              <h4> Correct Streak: </h4>
              <h4> {stats.streak} </h4>
            </div>
          </div>
        </div>
      </div>
    );
  };

  function guessed(x) {
    console.log(x);
    console.log(data.contentType);
    let stats = JSON.parse(localStorage.getItem("stats"));
    if (stats === null) {
      stats = { win: 0, loss: 0, streak: 0 };
    }
    if (x === data.contentType) {
      stats["win"] += 1;
      stats["streak"] += 1;
      localStorage.setItem("stats", JSON.stringify(stats));
      setState((s) => ({ ...s, page: 1 }));
    } else {
      stats["loss"] += 1;
      stats["streak"] = 0;
      localStorage.setItem("stats", JSON.stringify(stats));
      setState((s) => ({ ...s, page: 2 }));
    }
  }

  // const home = () => setState({ ...state, page: 0 });

  // const scroll = () => {
  //   console.log(data.contentType);
  //   if (state.mode === "down") {
  //     document.getElementById("guess").scrollIntoView({ behavior: "smooth" });
  //   } else {
  //     document.getElementById("learn").scrollIntoView({ behavior: "smooth" });
  //   }
  // };

  return (
    <Template state={state} setState={setState}>
      <div className="page-container-guess" id="guess">
        {state.page === 0 ? choose() : chosen()}
      </div>
    </Template>
  );
}

export default Pizzle;
