import "../assets/styles/App.css";
import { Interweave } from "interweave";
import { PieChart } from "react-minimal-pie-chart";
import Template from "../components/template";
import style from "../assets/styles/pizzle.module.css";

function Pizzle({ state, setState, data }) {
  const subtitle = (
    <p className="subtitle">
      Wikipedia or AI-Generated? Take a guess and test your skills!
    </p>
  );

  const choose = () => (
    <div className={style["pizzle"]}>
      {/* <header> {this.topbar()} </header> */}
      {subtitle}

      <div className={style["article-container"]}>
        <div className="article">
          <Interweave content={data.html} />
        </div>
      </div>

      <div className={style["choices"]}>
        <div className={style["button-container"]}>
          <button
            className={style["choice-button"]}
            onClick={() => guessed(true)}
          >
            <span>WIKIPEDIA</span>
          </button>
        </div>
        <div className={style["button-container"]}>
          <button
            className={style["choice-button"]}
            onClick={() => guessed(false)}
          >
            <span>AI GENERATED</span>
          </button>
        </div>
      </div>
    </div>
  );

  const chosen = () => {
    const stats = JSON.parse(localStorage.getItem("stats"));
    const answerbox =
      "answer-box " + (state.page === 1 ? "correct" : "incorrect");
    return (
      <div className={style["pizzle"]}>
        {subtitle}

        <div className={style["chosen-container"]}>
          <div className={answerbox}>
            <h2 className="answer-box">
              {state.page === 1 ? "Correct" : "Incorrect"}
            </h2>
            <h3 className="answer-box">
              {state.page === 1 ? "You're right! " : "You have been deceived! "}
              Today's article
              {data.contentType
                ? " was an actual Wikipedia article"
                : " was generated by AI"}
            </h3>
          </div>

          <div className={style["left-wrapper"]}>
            <div className="chosen-article">
              <div className="article">
                <Interweave content={data.html} />
              </div>
            </div>
            <div className={style["learn-more"]}>
              Want to find out more about this topic?
              <a
                target="_blank"
                rel="noreferrer"
                href={`https://letmegooglethat.com/?q=${data.title}`}
              >
                <span> Click here </span>
              </a>
            </div>
          </div>

          <div className={style["right-wrapper"]}>
            <div className={style["stats"]}>
              <h2> people deceived </h2>
              <div className={style["pie"]}>
                <PieChart
                  style={{ "grid-area": "1 / 1" }}
                  data={[
                    { title: "One", value: 10, color: "#D8D9DB" },
                    { title: "Two", value: 15, color: "#554F9C" },
                  ]}
                  lineWidth={40}
                  startAngle={270}
                />
                <h1 style={{ "grid-area": "1 / 1" }}>42%</h1>
              </div>
              <h3> your win rate </h3>
              <div className={style["bar"]}>
                <div
                  style={{
                    width: `${(stats.win / (stats.loss + stats.win)) * 100}%`,
                    height: "100%",
                    background: "#554F9C",
                    borderRadius: "2px",
                  }}
                />
              </div>
              <h3> Correct Streak of {stats.streak} </h3>
            </div>
          </div>
        </div>
      </div>
    );
  };

  function guessed(x) {
    console.log(x);
    console.log(data.contentType);
    let stats = JSON.parse(localStorage.getItem("stats"));
    if (stats === null) {
      stats = { win: 0, loss: 0, streak: 0 };
    }
    if (x === data.contentType) {
      stats["win"] += 1;
      stats["streak"] += 1;
      localStorage.setItem("stats", JSON.stringify(stats));
      setState((s) => ({ ...s, page: 1 }));
    } else {
      stats["loss"] += 1;
      stats["streak"] = 0;
      localStorage.setItem("stats", JSON.stringify(stats));
      setState((s) => ({ ...s, page: 2 }));
    }
  }

  return (
    <Template state={state} setState={setState} page={"q"}>
      <div className={style["page-container-pizzle"]} id="guess">
        {state.page === 0 ? choose() : chosen()}
      </div>
    </Template>
  );
}

export default Pizzle;
